### ISSUE TITLE
有几个疑问：

### ISSUE THREAD

**Issue by Hexianjie** [kingname/RemoteControl#1]
- _config.ini 要转为ASCII编码再运行，不然出现 ConfigParser.MissingSectionHeaderError 。。
  估计使用记事本编辑的。。。
  原因：在window下面用记事本编辑文件的时候，如果保存为UNICODE或UTF-8，分别会在文件的开头加上两个字节“\xFF\xFE”和三个字节“\xEF\xBB\xBF”。 
- 运行不成功，日记如下：
  2015-09-22 17:37:32 INFO 开始抓取邮件。
  2015-09-22 17:37:33 INFO 抓取邮件成功。
  2015-09-22 17:37:33 INFO 开始抓取subject和发件人
  2015-09-22 17:37:33 ERROR 抓取subject和发件人成功'NoneType' object has no attribute 'group'
  - 我的配置：
  
  [Slave]
  pophost = pop.sina.cn
  smtphost = smtp.sina.cn
  port = 25
  username = 14778860037@sina.cn
  password = *****
  
  [Boss]
  mail = hexianjie1995@qq.com
  timelimit = 1
- 发送邮件配置：  从hexianjie1995@qq.com 发送主题为 dir 的邮件到 14778860037@sina.cn。

**Comment by kingname** [comment]
这个程序进行了大量的重构，现在的版本可以运行了。请再测试一下。
